version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
  bundle-install: toshimaru/bundle-install@0.3.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-browsers
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:1.17.2
      - bundle-install/bundle-install
